# Numpy

This lesson will discuss the Numpy package, which does super-fast math in Python.

In [2]:
#import numpy package using the 'np' abbreviation
import numpy as np

Numpy does everything that our normal lists can do, and more. When we want to sort only a few values, we can use a standard python list. However, once we get to more values than that, a list can quickly become a performance bottleneck. Here's where we will discuss numpy arrays.

In [5]:
#Let's start with Python lists
a=[1,2,3]
b=[4,5,6]
print('a + b=', a+b)

a + b= [1, 2, 3, 4, 5, 6]


In [6]:
#Here's where we run into a problem. Let's try to multiply the two lists

try:
    print(a*b)
except TypeError:
    print('Lists cannot be multiplied in Python')

Lists cannot be multiplied in Python


To multiply lists of values, we must use numpy, Python's library for numerical computing. You can use numpy for everything from arithmetic to highly complex math. Numpy can even be your calculator. 

<b>Performance: Lists vs. numpy arrays</b>

In [11]:
#Numpy arrays are stored in memory in a much more efficient way than Python lists.
#Let's compare them to see the respective advantages

#create the objects
import numpy as np
my_array = np.arange(1000000)
my_list = list(range(1000000))

In [14]:
#%timeit
#now let's compare the two
%time for _ in range(10): my_array2 = my_array * 2

CPU times: user 26.5 ms, sys: 8.38 ms, total: 34.9 ms
Wall time: 35 ms


In [15]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 631 ms, sys: 183 ms, total: 814 ms
Wall time: 818 ms


In [16]:
#If we look at this, we can see that the numpy array is several times faster than lists. 
#This is why many scientific and data science applications use numpy when they can.

<b>Saving and loading arrays</b>

Numpy comes with built-in save and load ability. We can save the arrays to disk and then load them again.

In [46]:
#let's get our directory
import os
os.getcwd()
os.listdir()


['datetime_exercise.py',
 'baggage_two.ipynb',
 'baggage.ipynb',
 'numpy_practice.ipynb',
 'files_practice',
 'magicmethods_introduction.py',
 'file_system',
 'custom_object_topics',
 'saving_your_work',
 'functions.ipynb',
 'Games_and_Python_with_classes2-Copy1.ipynb',
 'matplotlib',
 '.ipynb_checkpoints',
 'easy_classes.ipynb',
 'reverse_strings_exercise.py']

<b>Numpy array basics</b>

In [7]:
#numpy has a basic object known as the array
#here's an array with only one number
a = np.array([1])
b=np.array(2)

In [8]:
print(a)
print(b)
a*b

[1]
2


array([2])

In [25]:
#More commonly, numpy arrays have only one value. We can initialize them with a Python list.
array_1 = [1, 2, 3]
a_1 = np.array(array_1)

#this is the same as
array_2 = np.array([4,5,6])
print(array_1, 'is a', type(array_1))
print(a_1, 'is a', type(array_2))

[1, 2, 3] is a <class 'list'>
[1 2 3] is a <class 'numpy.ndarray'>


We can add two numpy arrays together

In [ ]:
ar1 = np.array([1,2,3])
ar2 = np.array([2,4,6])
ar3 = ar1+ar2
print('ar1', ar1, '+', 'ar2', ar2, '=', ar3)

In [30]:
#Let's subtract two numpy arrays:

ar4 = ar1-ar2
print(ar4)

[-1 -2 -3]


In [32]:
#Let's multiply two arrays:
ar5 = ar1*ar2
print(ar5)

[ 2  8 18]


In [ ]:
#Let's divide two arrays
ar6 = ar1/ar2
print(ar6)

<i>Making arrays from functions</i>

We can also use functions to make arrays. One example of this is the `range` function.

In [39]:
c = np.array(range(1, 11)) #all the numbers from 1 to 11
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a_squared= lambda x: x**2
a_sq = np.array([a_squared(i) for i in range(1, 10)])
print(a_sq)

In [52]:
#Let's get the maximum and minimum values
print('This:', np.max(a_sq))
print('does the same thing as this:', a_sq.max())
#
print('Minimum:', np.min(a_sq))
print('Also the minimum: ', a_sq.min())

This: 81
does the same thing as this: 81
Minimum: 1
Also the minimum:  1


<b>Nested Arrays</b>

We can nest arrays inside one another to create matrices. To create a 3x3 matrix, we simply create an array consisting of three 1x3 subarrays.

In [ ]:
data = [[1,2,3], [4,5,6], [7,8,9]]
data_array = np.array(data)
print(data_array)

In [15]:
#we can do the same thing with lists of any length:
b=[[1,2],[3,4]]
b_array=np.array(b)
print(b_array)

[[1 2]
 [3 4]]


In [17]:
#or even different lengths
a=[1, [2,3]]
a_array = np.array(a)
print(a_array)

[1 list([2, 3])]


<b>Special types of arrays</b>

In [21]:
#We can make an array with all ones:
#make a single row numpy array
one_by_three_ones = np.ones(3)
print(one_by_three_ones)

[1. 1. 1.]


In [25]:
two_by_three_ones = np.ones((2, 3))
print(two_by_three_ones)
three_by_three_ones = np.ones((3,3))

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#Each array consists of only one datatype: we can choose these datatypes when we create 
#the array:

a=np.array([1,2,3])
#Let's get the type
print(a)
print(a.dtype)

[1 2 3]
int64


In [36]:
#Now let's make an array with integers and floats and see what happens
b=np.array([1, 2.4, 3])
print(b)
print(b.dtype)
#So the type has been made into "float" becuase it includes integers and floats

[1.  2.4 3. ]
float64


<b>Multidimensional arrays</b>

We can nest arrays inside one another to create matrices. To create a 3x3 matrix, we simply create an array consisting of three 1x3 subarrays.

In [17]:
#We can create a matrix with nested lists in numpy
data = [[1,2,3], [4,5,6], [7,8,9]]
data_array = np.array(data)

In [18]:
#Let's print out our array and get some information about it
print(data_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#Let's access the individual elements:
#The first row:
print('The first row is: ', data_array[0])
print('The second row is: ', data_array[1])
print('The third row is: ', data_array[2])

The first row is:  [1 2 3]
The second row is:  [4 5 6]
The third row is:  [7 8 9]


<b>Slicing Arrays</b>

In [30]:
#Let's access the elements within each row. It's indexed like a tuple. We start with the 
#outermost part of the array and move inwards.

#get the first row (as above):

data2 = [[1,2,3], [4,5,6], [7,8,9]]
data_array2 = np.array(data2)
print('The first row is: ', data_array2[0])
print('The first element of the first row is: ', data_array2[0, 0])
print('The second element of the first row is: ', data_array2[0, 1])
print('The third element of the first row is: ', data_array2[0, 2])
#Likewise, we access the second row of the matrix with
print('The second row is:', data_array2[1])
#get the second element of the third row
print('The second element of the third row is: ', data_array2[2,2])
#We can also index the elements from the end:
print('The last element of the first row is:', data_array2[0, -1])
print('The last row is:', data_array[-1])

The first row is:  [1 2 3]
The first element of the first row is:  1
The second element of the first row is:  2
The third element of the first row is:  3
The second element of the third row is:  9
The last element of the first row is: 3
The last row is: [7 8 9]


In [65]:
#Accessing elements by column
#make a list with list comprehension
a = [[i for i in range(1, 4)],[i for i in range(4, 7)],[i for i in range(7, 10)]]
#make it into an array
a = np.array(a)
print(a)
#The first column only
a[:,0]
#to second column only
a[:,1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

In [ ]:
#